### ISSUE TITLE
Example in readme need arg `-p`?

### ISSUE THREAD

**Issue by yihong0618** [jschwinger233/pdbattach#9]
In README 

```shell
sudo pdbattach $(pgrep -f test.py)

# is there need `-p` here`?
sudo pdbattach -p $(pgrep -f test.py)
```

**Comment by jschwinger233** [comment]
Thanks for the report, fixed in https://github.com/jschwinger233/pdbattach/pull/10. I also added a new example which I believe is useful.

Still there is something wrong in the project and I am looking into it, sorry for the inconvenience caused.
